language: objective-c
osx_image: xcode61
before_install:
    - git submodule update --init --recursive
script:
    - xcodebuild -project NetworkObjects/NetworkObjects.xcodeproj -scheme 'NetworkObjects' -sdk macosx -arch x86_64 clean build test CODE_SIGNING_REQUIRED=NO
    - xcodebuild -project NetworkObjects/NetworkObjects.xcodeproj -scheme 'NetworkObjects' -sdk iphonesimulator -arch i386 clean build test build CODE_SIGNING_REQUIRED=NO